name: Update 3D Contribution Calendar

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at 00:00 UTC
  workflow_dispatch:      # Allows manual trigger from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib numpy beautifulsoup4 requests

    - name: Generate 3D Contribution Calendar
      run: |
        python generate_3d_contrib.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add images/github_3d_contributions.png
        git commit -m "Auto-update 3D Contribution Calendar" || echo "No changes to commit"
        git push
